eureka:
  instance:
    prefer-ip-address: false
    homePageUrl: http://${eureka.instance.hostName}/${server.servlet.context-path}
    metadata-map:
      management:
        context-path: ${server.servlet.context-path}
  client:
    serviceUrl:
      defaultZone: http://localhost:8761/eureka/
      
  
management: 
  endpoints: 
    web: 
      exposure: 
        include: "*"

spring: 
   data:
     rest:
       basePath: /api
   boot:
     admin:
       discovery:
         converter:
           management-context-path: ${server.servlet.context-path}
   datasource:
     driver-class-name: org.postgresql.Driver
     initialization-mode: never     
     username: tad
     password: tad
   jpa:
     open-in-view: false
     database-platform: org.hibernate.dialect.PostgreSQLDialect
     generate-ddl: false
     database: POSTGRESQL    
     show-sql: true

   servlet:
     multipart:
      enabled: true
      file-size-threshold: 2KB 
      max-file-size: 5MB
      max-request-size: 5MB                   

logging:
  level:
    ROOT: INFO
    org.springframework.security: DEBUG    
    org.springframework.jdbc.core.JdbcTemplate: DEBUG
    org.springframework.jdbc.core.StatementCreatorUtils: TRACE    
    org.springframework.web: INFO
    org.hibernate: INFO
    com.buypower: DEBUG  

hystrix:          
  command:
    default:
      execution:
        isolation:
          strategy: SEMAPHORE
          thread:
            timeoutInMilliseconds: 301000
 

feign:   
  hystrix:
    enabled: true
  client:
    config: 
      default: 
        connectTimeout: 5000
        readTimeout: 300000    
        loggerLevel: basic
             
        
